"""
Database models for the AI Accountability Trust Engine.
"""

from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    Text,
    DateTime
)

from datetime import datetime

from database.db import Base


class DecisionRecord(Base):
    """
    Stores every AI decision as an immutable ledger entry.
    """

    __tablename__ = "decision_records"

    # Internal database ID
    id = Column(Integer, primary_key=True, index=True)

    # Unique decision ID received from Decision Engine
    decision_id = Column(String, unique=True, nullable=False, index=True)

    # Complete JSON payload received from Member 1
    payload = Column(Text, nullable=False)

    # Trust score generated by Trust Engine
    trust_score = Column(Float, nullable=False)

    # APPROVED / REJECTED
    status = Column(String, nullable=False)

    # Hash chain fields
    previous_hash = Column(Text, nullable=False)

    current_hash = Column(Text, nullable=False)

    # HMAC signature
    signature = Column(Text, nullable=False)

    # Future-proofing
    verification_version = Column(
        String,
        default="1.0"
    )

    # Timestamp
    timestamp = Column(
        DateTime,
        default=datetime.utcnow
    )